version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - transport.tcp.port=9500
      - http.port=9400
      - xpack.security.authc.accept_default_password=true
      - xpack.security.enabled=false
      - path.data=/storage/docker/elasticsearch-datadir/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/storage/docker/elasticsearch-datadir/data
    ports:
      - 9400:9400
      - 9500:9500

volumes:
  esdata1:
    driver: local